namespace PostSharp.LicenseServer;

/// <summary>
/// A license key registered on the license server. Maps to the <c>dbo.Licenses</c> table.
/// </summary>
public class License
{
    /// <summary>
    /// Gets or sets the license identifier. This value comes from the license key itself, so it is
    /// assigned by the application and not generated by the database.
    /// </summary>
    public int LicenseId { get; set; }

    public string LicenseKey { get; set; } = null!;

    public string ProductCode { get; set; } = null!;

    /// <summary>
    /// Gets or sets the order in which licenses are consumed. A negative value disables the license.
    /// </summary>
    public int Priority { get; set; }

    public DateTime CreatedOn { get; set; }

    /// <summary>
    /// Gets or sets the moment the license first exceeded its capacity, which starts the grace period.
    /// </summary>
    public DateTime? GraceStartTime { get; set; }

    /// <summary>
    /// Gets or sets the moment the last grace period warning email was sent.
    /// </summary>
    public DateTime? GraceLastWarningTime { get; set; }

    public ICollection<Lease> Leases { get; set; } = new List<Lease>();
}
