<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>

    <Product>PostSharp License Server</Product>
    <Company>PostSharp Technologies</Company>
    <Copyright>Copyright (c) PostSharp Technologies</Copyright>
    <Version>2025.1.0</Version>
  </PropertyGroup>

</Project>
