-- The schema of the license server on PostgreSQL. Run it once, against an empty database, before you
-- start the server for the first time. The server never creates the schema and never modifies it, so
-- an upgrade of the server makes no change to the database.
--
-- The names of the tables and of the columns are quoted, so they keep their capitals. The queries of
-- the server quote them the same way.
--
-- This schema has no HMAC column. The SQL Server schema has one, because installations created before
-- 2026 have it and the column is left in place there. Nothing writes it.

-- The comparison of a user name and of a machine name ignores the case, as it does on SQL Server,
-- whose default collation ignores it. A collation that is not deterministic is what makes a
-- comparison and a grouping ignore the case. It refuses the pattern operators, and no query of this
-- server applies one to these two columns.
CREATE COLLATION IF NOT EXISTS "license_server_ci" (
    provider = icu, locale = 'und-u-ks-level2', deterministic = false );

CREATE TABLE "Licenses" (
    -- The identifier comes from the license key and is not generated by the database.
    "LicenseId" integer NOT NULL,
    "LicenseKey" text NOT NULL,
    "ProductCode" character varying(50) NOT NULL,
    "Priority" integer NOT NULL,
    "CreatedOn" timestamp with time zone NOT NULL,
    "GraceStartTime" timestamp with time zone,
    "GraceLastWarningTime" timestamp with time zone,
    CONSTRAINT "PK_Licenses" PRIMARY KEY ("LicenseId")
);

CREATE TABLE "Leases" (
    "LeaseId" integer GENERATED BY DEFAULT AS IDENTITY,
    -- The lease this one replaces. Prolonging a lease and cancelling one both insert a row, so the
    -- table is the audit log and a row is never updated and never deleted.
    "OverwrittenLeaseId" integer,
    "LicenseId" integer NOT NULL,
    "StartTime" timestamp with time zone NOT NULL,
    "EndTime" timestamp with time zone NOT NULL,
    "UserName" character varying(200) COLLATE "license_server_ci" NOT NULL,
    "Machine" character varying(200) COLLATE "license_server_ci" NOT NULL,
    "AuthenticatedUser" character varying(200) NOT NULL,
    "Grace" boolean NOT NULL,
    CONSTRAINT "PK_Leases" PRIMARY KEY ("LeaseId"),
    -- The deletion of a license must not cascade through the chain of replaced leases, so both keys
    -- restrict instead of cascading. The page that deletes a license deletes the leases itself, the
    -- most recent one first.
    CONSTRAINT "FK_Leases_Leases" FOREIGN KEY ("OverwrittenLeaseId") REFERENCES "Leases" ("LeaseId") ON DELETE RESTRICT,
    CONSTRAINT "FK_Leases_Licenses" FOREIGN KEY ("LicenseId") REFERENCES "Licenses" ("LicenseId") ON DELETE RESTRICT
);

-- The index a lease request uses: it reads the leases that are open at the current time.
CREATE INDEX "IX_Leases_EndTime" ON "Leases" ("EndTime");

CREATE INDEX "IX_Leases_LicenseId" ON "Leases" ("LicenseId");

-- The index of the anti-join that finds the leases nothing has replaced.
CREATE INDEX "IX_Leases_OverwrittenLeaseId" ON "Leases" ("OverwrittenLeaseId");
