# This file is auto-generated by PostSharp.Engineering.

# See the OS_IMAGE_REPOSITORY comment in the Windows branch: the base image is a build-arg so
# that DockerBuild.ps1 can redirect it to a registry-local mirror without changing this file.
ARG OS_IMAGE=ubuntu:22.04
FROM ${OS_IMAGE}

# Prepare environment
ENV DEBIAN_FRONTEND=noninteractive
ENV RUNNING_IN_DOCKER=TRUE

# Set locale for consistent behavior regardless of host locale
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
ENV DOTNET_CLI_UI_LANGUAGE=en

# Install the prerequisites shared by the other components
RUN apt-get update && apt-get install -y \
    curl \
    wget \
    ca-certificates \
    libicu70 \
    libssl3 \
    && rm -rf /var/lib/apt/lists/*



# Install Git
RUN apt-get update && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*

RUN git config --system core.longpaths true && git config --system core.autocrlf false


# Install PowerShell 7
RUN wget -q https://github.com/PowerShell/PowerShell/releases/download/v7.5.2/powershell_7.5.2-1.deb_amd64.deb \
    && dpkg -i powershell_7.5.2-1.deb_amd64.deb \
    && rm powershell_7.5.2-1.deb_amd64.deb


# Download .NET Installer
RUN curl -sSL https://dot.net/v1/dotnet-install.sh -o /usr/local/bin/dotnet-install.sh \
    && chmod +x /usr/local/bin/dotnet-install.sh

ENV DOTNET_ROOT=/usr/share/dotnet
ENV PATH="${DOTNET_ROOT}:${PATH}"


# Install .NET Sdk 10.0.102
RUN /usr/local/bin/dotnet-install.sh --version 10.0.102 --install-dir $DOTNET_ROOT


# .NET Dump Tool
RUN dotnet tool install --global dotnet-dump

ENV PATH="/root/.dotnet/tools:${PATH}"


# Install PostgreSQL 17
RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc -o /etc/apt/trusted.gpg.d/postgresql.asc \
    && echo "deb http://apt.postgresql.org/pub/repos/apt jammy-pgdg main" > /etc/apt/sources.list.d/pgdg.list \
    && apt-get update \
    && apt-get install -y postgresql-17 \
    && rm -rf /var/lib/apt/lists/*

ENV PGBINDIR=/usr/lib/postgresql/17/bin
ENV PATH="${PGBINDIR}:${PATH}"


# Epilogue
# Configure .NET SDK
ENV DOTNET_NOLOGO=1
